//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public int id { get; set; }
        public Nullable<int> university_id { get; set; }
        public string name { get; set; }
        public string teacher_name { get; set; }
    
        public virtual University University { get; set; }
    }
}
